### ISSUE TITLE
Crash when exiting preferences with back button

### ISSUE THREAD

**Issue by AnaelMobilia** [meefik/busybox#89]
Hello,

The apps crash when the preference screen is exited with the back button
```
12-28 22:03:05.941 12484-12484/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.meefik.busybox, PID: 12484
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.drawerlayout.widget.DrawerLayout.isDrawerOpen(int)' on a null object reference
        at ru.meefik.busybox.SettingsActivity.onBackPressed(SettingsActivity.java:124)
        at android.app.Activity.onKeyUp(Activity.java:2520)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2669)
        at android.app.Activity.dispatchKeyEvent(Activity.java:2773)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2347)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4637)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4593)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4271)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4133)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4328)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4133)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4304)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4474)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2330)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1934)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1925)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2307)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:5763)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```
Xperia E5 F3311 / Android 6.0 / busybox 1.31.1-44

Regards,
Anael

**Comment by meefik** [comment]
Thanks for the report, fixed in v1.31.1-45
